### ISSUE TITLE
which file need be created?

### ISSUE THREAD

**Issue by SeekPoint** [shagunsodhani/CNN-Sentence-Classifier#3]
rzai@rzai00:~/prj/CNN-Sentence-Classifier$ python3 app/train.py --data_dir=sample_dataset/ --embedding_file_path=/media/rzai/ai_data/glove.6B.200d.txt --model_name=cnn_static
Using Theano backend.
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Reading word vectors.
Found 400000 word vectors.
Processing input data
Found 10662 texts.
Found 19498 unique tokens.
Shape of data tensor: (10662, 56)
Shape of label tensor: (10662, 2)
Preparing embedding matrix.
Traceback (most recent call last):
  File "app/train.py", line 90, in <module>
    main()
  File "app/train.py", line 20, in main
    train(args)
  File "app/train.py", line 71, in train
    embedding_matrix[i] = embedding_vector
ValueError: could not broadcast input array from shape (200) into shape (100)
rzai@rzai00:~/prj/CNN-Sentence-Classifier$ python3 app/train.py --data_dir=sample_dataset/ --embedding_file_path=/media/rzai/ai_data/glove.6B.100d.txt --model_name=cnn_static
Using Theano backend.
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Reading word vectors.
Found 400000 word vectors.
Processing input data
Found 10662 texts.
Found 19498 unique tokens.
Shape of data tensor: (10662, 56)
Shape of label tensor: (10662, 2)
Preparing embedding matrix.
Defining model.
Train on 9596 samples, validate on 1066 samples
Epoch 1/10
9568/9596 [============================>.] - ETA: 0s - loss: 0.6636 - acc: 0.6422Epoch 00000: val_loss improved from inf to 0.55422, saving model to model/weights.best.hdf5
Traceback (most recent call last):
  File "app/train.py", line 90, in <module>
    main()
  File "app/train.py", line 20, in main
    train(args)
  File "app/train.py", line 83, in train
    nb_epoch=args.num_epochs, batch_size=args.batch_size, callbacks=callbacks_list)
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 620, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1106, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 844, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 40, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 296, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 2423, in save
    save_model(self, filepath, overwrite)
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 48, in save_model
    f = h5py.File(filepath, 'w')
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 85, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5f.pyx", line 90, in h5py.h5f.create (h5py/h5f.c:1984)
OSError: unable to create file (File accessibilty: Unable to open file)
rzai@rzai00:~/prj/CNN-Sentence-Classifier$ 
rzai@rzai00:~/prj/CNN-Sentence-Classifier$ 
rzai@rzai00:~/prj/CNN-Sentence-Classifier$

**Comment by shagunsodhani** [comment]
> ValueError: could not broadcast input array from shape (200) into shape (100)

This error is because of difference in embedding dimensions. Expected dimensionality is 100 while the vectors have a dimensionality of 200. To set the dimensionality, use the [`--embedding_dim` option](https://github.com/shagunsodhani/CNN-Sentence-Classifier/blob/master/app/utils/argumentparser.py)

> OSError: unable to create file (File accessibilty: Unable to open file)

Did you run `mkdir model`?

**Comment by SeekPoint** [comment]
fixed!!!
thanks
